name: CI-SLimOptim

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  # Trigger the workflow on push to master or pull request
  # to be merged in master
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        version: ['1.6', '1.7', '1.8', '1.9', '1.10', '1']
        os: [ubuntu-latest]
        arch: [x64]

        include:
          - os: macos-latest
            version: '1'
            arch: x64

    steps:
      - name: Checkout SlimOptim
        uses: actions/checkout@v3

      - name: Setup julia
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}

      - name: Run tests
        uses: julia-actions/julia-runtest@latest
